# Hochschule Bonn-Rhein-Sieg

# Mathematics for Robotics and Control, WS19

# 01 - Introduction to Python for Mathematics

In [5]:
###### Run this cell (Ctrl + enter) when you first open 
###### the notebook to import all packages
import numpy as np
import numpy.linalg as linalg
import scipy as scp
import sympy as sp
import matplotlib.pyplot as plt
Requirements for passing the seminar
The seminar will be graded based on your performance in the following three areas:
1. Regular presence and delivery of homework in satisfying quality: 40% of final grade.
2. Delivery of seminar report in satisfying quality: 40% of final grade.
3. Pitching your seminar report in the second exam period: 20% of final grade.

Should your performance be insufficient in one of the above areas, then the seminar as whole counts as failed. The seminar report has to be delivered by 15.08.2019. It will be an annotated bibliography comprising reading reports on the top 30 papers collected on a subject of your choice. Each reading report shall not consist of less than 4000 characters (without space). The final pitch will consist of a 5 minutes presentation followed by 2 minutes Q&A. In the pitch you are expected to identify the three main challenges in the research area, which you chose for your ISW. For each challenge you should provide at least three references that share / support your assessment of the importance and relevance of the challenge.

The main learning paradigm of the seminar report is inductive learning (i.e. learning from positive and negative examples). This requires that students regularly present their ideas and their work and obtain constructive criticism, which in turn requires the students to regularly attend the seminar (minimum 80% of all sessions). Should you become sick then please, provide a medical certificate.


import imageio
from skimage import transform
%matplotlib inline

To find the documentation for a function, use a ? after the function as below and run the cell

In [6]:
np.array?

## Creating a rotation matrix

Let's suppose that we have a robot that is located at the origin of the world frame, such that its local coordinate system is aligned with the world frame. The robot now rotates counterclockwise by $\frac{\pi}{4}$ radians around the $z$-axis. Our task is to define a rotation matrix that expresses the robot's rotation; in other words, denoting the world frame by $A$ and the robot frame by $B$, we need to express the matrix ${}^A_BR$.

In [9]:
def get_rotation_matrix_z_axis(theta: float) -> np.array:
    return np.array([[np.cos(theta), -1 * np.sin(theta), 0],
                     [np.sin(theta), np.cos(theta), 0],
                     [0, 0, 1]])
        
def get_rotation_matrix_x_axis(theta: float) -> np.array:
    return np.array([[1, 0 ,0],
                    [0, np.cos(theta), -1 * np.sin(theta)],
                    [0, np.sin(theta), np.cos(theta)]])

def get_rotation_matrix_y_axis(theta: float) -> np.array:
    return np.array([[np.cos(theta), 0, np.sin(theta)],
                     [0, 1 ,0],
                     [-1 * np.sin(theta), 0 , np.cos(theta)]])
    
theta = np.pi / 4.

print(get_rotation_matrix_z_axis(theta))
print(get_rotation_matrix_x_axis(theta))
print(get_rotation_matrix_y_axis(theta))

[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
[[ 1.          0.          0.        ]
 [ 0.          0.70710678 -0.70710678]
 [ 0.          0.70710678  0.70710678]]
[[ 0.70710678  0.          0.70710678]
 [ 0.          1.          0.        ]
 [-0.70710678  0.          0.70710678]]


## Plotting the frames

Let's now plot the world frame and the rotated frame of the robot together.

In [ ]:
# plot the world frame

# plot the robot frame

# set some plot properties

## Translating frames

Let's now assume that, instead of rotating, the robot translates by $3$ units along the $x$-axis and $5$ units along the $y$-axis. We could express this in Python as follows:

In [ ]:
# define the current position

# define the translation

# define the new position

## Plotting the frames

Let's now plot the world frame and the translated frame of the robot.

In [ ]:
# plot the world frame

# plot the robot frame

# set some plot properties

## Combining rotation and translation into a homogeneous transformation matrix

Let's now assume that the robot both rotates by $\frac{\pi}{4}$ around the $z$-axis and translates by $3$ units along the $x$-axis and $5$ units along the $y$-axis. As we know from the lecture, rotations and translations can be expressed together in a so-called homogeneous transformation matrix. Let's perform this transformation in Python.

In [ ]:

Requirements for passing the seminar
The seminar will be graded based on your performance in the following three areas:
1. Regular presence and delivery of homework in satisfying quality: 40% of final grade.
2. Delivery of seminar report in satisfying quality: 40% of final grade.
3. Pitching your seminar report in the second exam period: 20% of final grade.

Should your performance be insufficient in one of the above areas, then the seminar as whole counts as failed. The seminar report has to be delivered by 15.08.2019. It will be an annotated bibliography comprising reading reports on the top 30 papers collected on a subject of your choice. Each reading report shall not consist of less than 4000 characters (without space). The final pitch will consist of a 5 minutes presentation followed by 2 minutes Q&A. In the pitch you are expected to identify the three main challenges in the research area, which you chose for your ISW. For each challenge you should provide at least three references that share / support your assessment of the importance and relevance of the challenge.

The main learning paradigm of the seminar report is inductive learning (i.e. learning from positive and negative examples). This requires that students regularly present their ideas and their work and obtain constructive criticism, which in turn requires the students to regularly attend the seminar (minimum 80% of all sessions). Should you become sick then please, provide a medical certificate.

# specify the original position, p_b, of the robot (in homogeneous coordinates)

# define the translation

# convert p_b into a column vector

# create the transformation matrix

# transform p_b

# select and print the translation column

# select and print the last row of the matrix

# select and print the translation matrix

## Plotting the frames

Let's plot the world frame and the transformed robot frame.

In [ ]:
# plot the world frame

# plot the robot frame

# set some plot properties

## Symbolic mathematics using symbolic Python

In [ ]:
# create a symbolic variable, x

# create a function of x

# substitute values into y

# differentiate y with respect to x

# integrate y with respect to x

# substitute values into y_prime

## Loading files and plotting 3D data

In [ ]:
from mpl_toolkits.mplot3d import Axes3D

# load data

# create a 3D scatter plot

## Loading and manipulating images

In [ ]:
# load an image using scipy

# display the image

# resize the image and display the resized version

# find edges in the image

## Optimising functions using scipy

In [ ]:
# define a function to return the square of a number
def f(x: float) -> float:
    raise NotImplementedError()

# define a function to return the differential of x**2
def f_prime(x: float) -> float:
    raise NotImplementedError()

# optimising x**2 starting at x = 0.5 (the minimum occurs 
# at x = 0, so that's the expected solution)